### ISSUE TITLE
const {query, variable={}} = request.payload; does not set query 

### ISSUE THREAD

**Issue by jschimmoeller** [reindexio/graphql-nodejs-newsfeed#1]
i switched it to this:

const query = request.payload, variables= {};

**Comment by freiksenet** [comment]
Payload should include both query and variables, so that one can use variables in their query. The thing might not work correctly if you don't have content type set on your request.

**Comment by marksoper** [comment]
I noticed a related phenomenon during debugging with node-inspector. While stepping-through the program, the expression:

```
const {query, variables = {}} = request.payload;
```

doesn't seem to be completed (i.e. query variable not defined) until after the subsequent expression is run:

```
  const result = await graphql(
    Schema,
    query,
    {
      db: request.db,
      userId: '1'
    },
    variables
  );
```

Not sure why, maybe an effect of Babel transpilation.
